import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { createForm, deleteForm, loadForms, loadMessages, loadSubmissions, sendMessage, updateForm, updateSubmission, type NetworkForm, type NetworkMessage, type NetworkSubmission } from './formsNetwork'

const slugify=(v:string)=>v.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
export default function FormsNetworkWorkspace(){
  const [forms,setForms]=useState<NetworkForm[]>([]); const [subs,setSubs]=useState<NetworkSubmission[]>([]); const [formId,setFormId]=useState(''); const [selected,setSelected]=useState<NetworkSubmission|null>(null); const [messages,setMessages]=useState<NetworkMessage[]>([]); const [notice,setNotice]=useState('');
  const refresh=async()=>{ const next=await loadForms(); setForms(next); const active=formId||next[0]?.id||''; if(!formId&&active)setFormId(active); setSubs(await loadSubmissions(active||undefined)); }
  useEffect(()=>{ void refresh().catch(e=>setNotice(e.message)); const t=window.setInterval(()=>void refresh().catch(()=>{}),2500); return()=>window.clearInterval(t)},[formId])
  const active=forms.find(f=>f.id===formId); const visible=useMemo(()=>subs.filter(s=>!formId||s.form_id===formId),[subs,formId])
  const openThread=async(s:NetworkSubmission)=>{ setSelected(s); setMessages(await loadMessages(s.id)) }
  const create=async(e:FormEvent<HTMLFormElement>)=>{ e.preventDefault(); const el=e.currentTarget; const d=new FormData(el); const title=String(d.get('title')||'').trim(); const questionLines=String(d.get('questions')||'').split('\n').map(x=>x.trim()).filter(Boolean); await createForm({title,slug:String(d.get('slug')||'').trim()||slugify(title),eyebrow:String(d.get('eyebrow')||'EBG FORM'),description:String(d.get('description')||''),status:String(d.get('status')||'draft') as NetworkForm['status'],submitMessage:String(d.get('submitMessage')||'Thanks — your response has been received.'),questions:questionLines.map((line,i)=>{const [label,type='text']=line.split('|').map(x=>x.trim());return {label,key:slugify(label).replaceAll('-','_'),type:(['text','email','number','textarea','select'].includes(type)?type:'text') as any,required:true,position:i,options:null,placeholder:null}})}); el.reset(); setNotice('Form created.'); await refresh() }
  const reply=async(e:FormEvent<HTMLFormElement>)=>{ e.preventDefault(); if(!selected)return; const el=e.currentTarget; const d=new FormData(el); const body=String(d.get('body')||'').trim(); if(!body)return; await sendMessage(selected.id,body); el.reset(); setMessages(await loadMessages(selected.id)); setNotice('Message sent to applicant.') }
  return <div className="forms-network">
    <section className="panel forms-network-hero"><div><p className="eyebrow">EBG FORMS NETWORK</p><h2>Create once. Share anywhere.</h2><p>Build forms for any EBG project, publish a clean forms.ebgplus.app link, watch responses arrive live, and contact applicants without leaving Studio.</p></div><a className="button secondary" href="https://forms.ebgplus.app" target="_blank" rel="noreferrer">Open public Forms ↗</a></section>
    <section className="forms-network-grid"><aside className="panel"><h3>Forms</h3>{forms.map(f=><button className={'forms-network-form '+(f.id===formId?'active':'')} key={f.id} onClick={()=>setFormId(f.id)}><strong>{f.title}</strong><span>{f.status} · forms.ebgplus.app/{f.slug}</span></button>)}{active&&<div className="forms-network-actions"><select value={active.status} onChange={e=>void updateForm(active.id,{status:e.target.value as NetworkForm['status']}).then(refresh)}><option value="draft">Draft</option><option value="open">Open</option><option value="closed">Closed</option></select><button className="button danger" onClick={()=>{if(confirm('Delete this form and its responses?'))void deleteForm(active.id).then(()=>{setFormId('');return refresh()})}}>Delete</button></div>}</aside>
      <div className="panel"><div className="forms-network-title"><div><p className="eyebrow">LIVE RESPONSES</p><h3>{active?.title||'Responses'}</h3></div><span>{visible.length} total</span></div><div className="forms-network-responses">{visible.map(s=><article key={s.id}><div><strong>{s.respondent_email||'Anonymous applicant'}</strong><small>{new Date(s.created_at).toLocaleString()}</small></div><select value={s.status} onChange={e=>void updateSubmission(s.id,{status:e.target.value as NetworkSubmission['status']}).then(refresh)}><option value="new">New</option><option value="reviewing">Reviewing</option><option value="contacted">Contacted</option><option value="accepted">Accepted</option><option value="declined">Declined</option></select><button className="button secondary" onClick={()=>void openThread(s)}>Open & message</button></article>)}</div></div>
    </section>
    <section className="panel"><p className="eyebrow">CREATE FORM</p><h3>New network form</h3><form className="form-grid" onSubmit={create}><label>Title<input name="title" required /></label><label>Slug<input name="slug" placeholder="auto-created-from-title" /></label><label>Eyebrow<input name="eyebrow" defaultValue="EBG FORM" /></label><label>Status<select name="status" defaultValue="draft"><option value="draft">Draft</option><option value="open">Open now</option><option value="closed">Closed</option></select></label><label className="full">Description<textarea name="description" /></label><label className="full">Questions<textarea name="questions" placeholder={'Name | text\nEmail | email\nTell us about yourself | textarea'} required /></label><label className="full">Confirmation message<input name="submitMessage" defaultValue="Thanks — your response has been received." /></label><div className="full"><button className="button">Create form</button></div></form></section>
    {selected&&<section className="panel forms-network-thread"><button className="text-link" onClick={()=>setSelected(null)}>← Close response</button><h3>{selected.respondent_email||'Applicant'}</h3><div className="forms-network-answers">{Object.entries(selected.answers).map(([k,v])=><div key={k}><small>{k}</small><span>{String(v)}</span></div>)}</div><textarea defaultValue={selected.internal_notes} placeholder="Internal staff notes" onBlur={e=>void updateSubmission(selected.id,{internal_notes:e.target.value}).then(()=>setNotice('Notes saved.'))}/><div className="forms-network-messages">{messages.map(m=><p key={m.id}><span>{m.sender_account_id===selected.submitted_by?'Applicant':'EBG Team'}</span>{m.body}<small>{new Date(m.created_at).toLocaleString()}</small></p>)}</div><form onSubmit={reply}><textarea name="body" placeholder="Message applicant…" required/><button className="button">Send message</button></form></section>}
    {notice&&<div className="message"><span>{notice}</span><button onClick={()=>setNotice('')}>×</button></div>}
  </div>
}
