import { useEffect, useState } from 'react'
import { cleanPlatformLinks, platforms } from './musicDistribution'
import type { Platform } from './musicDistribution'
import { db } from '../../src/lib/supabase'
import { requireFreshSession } from '../../src/lib/auth'
import { brandedReleaseLink, cleanLinkSlug } from './streamingLinks'
type Release={id:string;title:string;cover:string;publishStatus:string;streamingLinks?:Partial<Record<Platform,string>>}
type Link={project_id:string;release_id:string;slug:string}
export default function MusicDistributionPanel({projectId,release,artistName,onSave}:{projectId:string;release:Release;artistName:string;onSave:(patch:{streamingLinks:Partial<Record<Platform,string>>})=>Promise<boolean>}) {
  const [slug,setSlug]=useState(()=>`${cleanLinkSlug(artistName.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''))||'artist'}/${cleanLinkSlug(release.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''))||'release'}`),[savedSlug,setSavedSlug]=useState(''),[links,setLinks]=useState(release.streamingLinks||{}),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[message,setMessage]=useState('')
  const query=`project_id=eq.${encodeURIComponent(projectId)}&release_id=eq.${encodeURIComponent(release.id)}`
  useEffect(()=>{let active=true;requireFreshSession().then(session=>db.select<Link>('studio_streaming_links',`${query}&limit=1`,session.access_token)).then(rows=>{if(active){if(rows[0]){setSavedSlug(rows[0].slug);setSlug(rows[0].slug)}setLoaded(true)}}).catch(()=>{if(active)setMessage('Streaming links could not be loaded. Reopen this page to retry.')});return()=>{active=false}},[query])
  const save=async()=>{setBusy(true);try{const clean=cleanLinkSlug(slug);if(clean!==slug.trim().toLowerCase()||!clean)throw new Error('Use 2–60 lowercase letters, numbers or hyphens, optionally followed by /release-name (2–80 characters).');await requireFreshSession();if(!await onSave({streamingLinks:cleanPlatformLinks(links)}))throw new Error('Platform links could not be saved. Try again.');const token=(await requireFreshSession()).access_token;const values={project_id:projectId,release_id:release.id,slug:clean};if(savedSlug)await db.update<Link>('studio_streaming_links',query,values,token);else await db.insert<Link>('studio_streaming_links',values,token);setSavedSlug(clean);setMessage('Streaming link saved. Artwork and release updates sync automatically.')}catch(e){const text=e instanceof Error?e.message:'Streaming link could not be saved.';setMessage(/duplicate key/i.test(text)?'That custom address is already in use. Choose another name.':text)}finally{setBusy(false)}}
  const url=savedSlug?brandedReleaseLink(savedSlug):''
  return <section className="music-distribution"><p className="eyebrow">STREAMING LINKS</p><h3>{release.title}</h3>{release.cover&&<img className="distribution-release-cover" src={release.cover} alt={`${release.title} cover`}/>}<p>Uses this release’s saved cover and audio automatically. Add platform destinations when your music is available there.</p><label>Custom EBG+ address<input disabled={busy} value={slug} onChange={e=>setSlug(e.target.value.toLowerCase())} placeholder="bijounicole/step-on-up"/></label><p className="music-link-preview">{brandedReleaseLink(slug)}</p><div className="music-v2-step-grid">{platforms.map(p=><label key={p.id}>{p.name}<input disabled={busy} type="url" placeholder={`https://${p.host}/…`} value={links[p.id]||''} onChange={e=>setLinks({...links,[p.id]:e.target.value})}/></label>)}</div><div className="music-v2-step-actions"><button className="button" type="button" disabled={busy||!loaded} onClick={()=>void save()}>{busy?'Saving…':savedSlug?'Save streaming link':'Generate streaming link'}</button>{url&&['live','scheduled'].includes(release.publishStatus)&&<><a className="button secondary" href={url} target="_blank" rel="noreferrer">Open streaming page ↗</a><button type="button" className="button secondary" onClick={async()=>{try{await navigator.clipboard.writeText(url);setMessage('Streaming link copied.')}catch{setMessage(url)}}}>Copy link</button></>}</div>{!['live','scheduled'].includes(release.publishStatus)&&<p>You can reserve a link now. Its public page becomes available when you publish or schedule the release.</p>}{message&&<p role="status">{message}</p>}</section>
}
