import { useEffect, useMemo, useState } from 'react'
import type { FormEvent } from 'react'
import { loadStudioInbox, loadStudioThread, markStudioThreadRead, sendStudioInboxMessage, setStudioConversationState, type StudioInboxForm, type StudioInboxMessage, type StudioInboxSubmission } from './inboxNetwork'

type Filter='all'|'unread'|'waiting'|'resolved'
export default function StudioInbox(){
  const [forms,setForms]=useState<StudioInboxForm[]>([])
  const [submissions,setSubmissions]=useState<StudioInboxSubmission[]>([])
  const [messages,setMessages]=useState<StudioInboxMessage[]>([])
  const [thread,setThread]=useState<StudioInboxMessage[]>([])
  const [active,setActive]=useState<StudioInboxSubmission|null>(null)
  const [filter,setFilter]=useState<Filter>('all')
  const [notice,setNotice]=useState('')
  const refresh=async()=>{const data=await loadStudioInbox();setForms(data.forms);setSubmissions(data.submissions);setMessages(data.messages)}
  useEffect(()=>{void refresh().catch(e=>setNotice(e.message));const timer=window.setInterval(()=>void refresh().catch(()=>{}),3000);return()=>window.clearInterval(timer)},[])
  const formTitle=(id:string)=>forms.find(f=>f.id===id)?.title??'EBG Application'
  const unreadFor=(id:string)=>messages.filter(m=>m.submission_id===id&&!m.read_by_staff).length
  const latestFor=(id:string)=>messages.find(m=>m.submission_id===id)
  const visible=useMemo(()=>submissions.filter(s=>filter==='all'||(filter==='unread'?unreadFor(s.id)>0:filter==='waiting'?s.conversation_state==='waiting_on_ebg':s.conversation_state==='resolved')),[submissions,messages,filter])
  const open=async(sub:StudioInboxSubmission)=>{setActive(sub);await markStudioThreadRead(sub.id).catch(()=>{});setThread(await loadStudioThread(sub.id));await refresh()}
  const send=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!active)return;const el=event.currentTarget;const data=new FormData(el);const body=String(data.get('body')||'').trim();if(!body)return;await sendStudioInboxMessage(active.id,body,String(data.get('senderLabel')||'EBG Studio'));el.reset();setThread(await loadStudioThread(active.id));await refresh();setNotice('Message sent.')}
  const updateState=async(state:'open'|'waiting_on_ebg'|'waiting_on_applicant'|'resolved')=>{if(!active)return;await setStudioConversationState(active.id,state);setActive({...active,conversation_state:state});await refresh();setNotice('Conversation updated.')}
  return <div className="studio-inbox">
    <section className="panel studio-inbox-hero"><div><p className="eyebrow">EBG COMMUNICATIONS</p><h2>Applicant Inbox</h2><p>Every application conversation across the network, in one staff inbox.</p></div><div className="studio-inbox-stats"><article><strong>{submissions.reduce((sum,s)=>sum+unreadFor(s.id),0)}</strong><span>unread</span></article><article><strong>{submissions.filter(s=>s.conversation_state==='waiting_on_ebg').length}</strong><span>waiting on EBG</span></article></div></section>
    <section className="panel"><div className="studio-inbox-toolbar"><div><button className={filter==='all'?'active':''} onClick={()=>setFilter('all')}>All</button><button className={filter==='unread'?'active':''} onClick={()=>setFilter('unread')}>Unread</button><button className={filter==='waiting'?'active':''} onClick={()=>setFilter('waiting')}>Waiting on EBG</button><button className={filter==='resolved'?'active':''} onClick={()=>setFilter('resolved')}>Resolved</button></div><span>{visible.length} conversations</span></div><div className="studio-inbox-list">{visible.map(sub=>{const latest=latestFor(sub.id);const unread=unreadFor(sub.id);return <button className={'studio-inbox-row '+(unread?'unread':'')} key={sub.id} onClick={()=>void open(sub)}><div className="studio-inbox-avatar">{String(sub.answers?.legalName??sub.respondent_email??'A').slice(0,1).toUpperCase()}</div><div><div className="studio-inbox-row-head"><strong>{String(sub.answers?.legalName??sub.respondent_email??'Applicant')}</strong><span>{formTitle(sub.form_id)}</span></div><p>{latest?.body??'No messages yet.'}</p><small>{sub.conversation_state?.replaceAll('_',' ')??'open'} · {new Date(latest?.created_at??sub.created_at).toLocaleString()}</small></div>{unread>0&&<b>{unread}</b>}</button>})}</div></section>
    {active&&<section className="panel studio-inbox-thread"><div className="studio-inbox-thread-head"><div><p className="eyebrow">PRIVATE THREAD</p><h3>{String(active.answers?.legalName??active.respondent_email??'Applicant')}</h3><span>{formTitle(active.form_id)} · {active.conversation_state?.replaceAll('_',' ')??'open'}</span></div><button className="button secondary" onClick={()=>setActive(null)}>Close</button></div><div className="studio-inbox-state-actions"><button onClick={()=>void updateState('open')}>Open</button><button onClick={()=>void updateState('waiting_on_ebg')}>Waiting on EBG</button><button onClick={()=>void updateState('waiting_on_applicant')}>Waiting on applicant</button><button onClick={()=>void updateState('resolved')}>Resolve</button></div><div className="studio-inbox-chat">{thread.map(message=><article className={message.sender_account_id===active.submitted_by?'applicant':'staff'} key={message.id}><strong>{message.sender_account_id===active.submitted_by?'Applicant':message.sender_label||'EBG Team'}</strong><p>{message.body}</p><small>{new Date(message.created_at).toLocaleString()}</small></article>)}</div><form className="studio-inbox-compose" onSubmit={send}><label>Send as<select name="senderLabel" defaultValue="EBG Studio"><option>EBG Studio</option><option>EBG Casting</option><option>EBG Team</option></select></label><label className="full">Message<textarea name="body" required placeholder="Write a message to the applicant…"/></label><div className="full"><button className="button">Send message</button></div></form></section>}
    {notice&&<div className="message"><span>{notice}</span><button onClick={()=>setNotice('')}>×</button></div>}
  </div>
}
