import { useEffect, useState } from 'react'
import { uploadStudioProjectMedia } from '../../src/lib/studioData'
import { masterStereo } from './audioMastering'
import type { MasterPreset } from './audioMastering'
import StudioAudioSources from './StudioAudioSources'
type Track = { id:string; title:string; audioUrl:string; originalAudioUrl?:string; losslessUrl?:string; losslessMimeType?:string; atmosUrl?:string }
export default function StudioMastering({ projectId, track, onSave, onBusyChange }: {projectId:string;track:Track;onSave:(patch:Partial<Track>)=>Promise<boolean>;onBusyChange?:(busy:boolean)=>void}) {
  const [preset,setPreset]=useState<MasterPreset>('clean'),[busy,setBusy]=useState(false),[result,setResult]=useState<Blob|null>(null),[preview,setPreview]=useState(''),[message,setMessage]=useState('')
  useEffect(()=>{onBusyChange?.(busy)},[busy])
  useEffect(()=>{setResult(null);setMessage('')},[track.audioUrl,preset])
  useEffect(()=>{if(!result){setPreview('');return}const url=URL.createObjectURL(result);setPreview(url);return()=>URL.revokeObjectURL(url)},[result])
  const render=async()=>{setBusy(true);setMessage('Rendering stereo master…');try{setResult(await masterStereo(track.audioUrl,preset));setMessage('Preview ready. Compare before applying. Export is 24-bit PCM WAV at 44.1 kHz.')}catch(e){setMessage(e instanceof Error?e.message:'Mastering failed.')}finally{setBusy(false)}}
  const apply=async()=>{if(!result)return;setBusy(true);try{const audioUrl=await uploadStudioProjectMedia(new File([result],`${track.id}-master.wav`,{type:'audio/wav'}),projectId,`music/masters/${track.id}`);const fromLossless=track.losslessUrl===track.audioUrl;const patch={audioUrl,originalAudioUrl:track.originalAudioUrl||track.audioUrl,losslessUrl:fromLossless?audioUrl:'',losslessMimeType:fromLossless?'audio/wav':'',atmosUrl:''};if(await onSave(patch)){setResult(null);setMessage('Stereo master applied. Original audio retained. Alternate audio mixes were cleared so playback uses this version.')}else setMessage('Could not apply the master. Your preview is retained; try again.')}catch(e){setMessage(e instanceof Error?e.message:'Master could not be uploaded. You can download the WAV instead.')}finally{setBusy(false)}}
  return <section className="music-wizard-track"><h4>{track.title} · mastering</h4><p>Stereo EQ, gentle compression, and sample-peak normalization with a −1 dBFS ceiling. Review on headphones before applying. This is not LUFS or true-peak certification.</p><label>Sound<select disabled={busy} value={preset} onChange={e=>setPreset(e.target.value as MasterPreset)}><option value="clean">Clean</option><option value="warm">Warm</option><option value="bright">Bright</option></select></label><label>Current audio<audio controls preload="none" src={track.audioUrl} /></label><button className="button secondary" disabled={busy} type="button" onClick={()=>void render()}>{busy?'Processing…':'Preview stereo master'}</button>{preview&&<><label>Mastered preview<audio controls src={preview} /></label><div className="music-v2-step-actions"><a className="button secondary" href={preview} download={`${track.title}-master.wav`}>Download WAV</a><button className="button" disabled={busy} type="button" onClick={()=>void apply()}>Use this master</button></div></>}
    <p>WAV/FLAC preserve the audio they contain. Converting an MP3 does not restore lost detail. A converted file is not automatically marked as an original lossless master.</p>
    {track.originalAudioUrl && <button className="button secondary" disabled={busy} type="button" onClick={async()=>{setBusy(true);try{if(await onSave({audioUrl:track.originalAudioUrl,originalAudioUrl:undefined,losslessUrl:'',losslessMimeType:'',atmosUrl:''}))setMessage('Original audio restored. Add alternate formats if needed.')}catch(e){setMessage(e instanceof Error?e.message:'Original could not be restored.')}finally{setBusy(false)}}}>Restore original audio</button>}
    <StudioAudioSources onBusyChange={onBusyChange} key={`${track.id}-${track.losslessUrl}-${track.atmosUrl}`} projectId={projectId} track={track} onSave={onSave} />
    <p>Dolby Atmos requires an actual spatial mix and encoder. Upload an existing Atmos DD+ JOC playback mix above; this tool does not create Atmos from stereo.</p>{message&&<p role="status">{message}</p>}
  </section>
}
